### ISSUE TITLE
Confirm whether 0's in dataset reflect missing values

### ISSUE THREAD

**Issue by Colleen-ODonnell** [Colleen-ODonnell/KenyaPovertyTargetingModel#7]

**Comment by steveofconnell** [comment]
and the converse -- whether missings (NAs, ., or other values for missing) can be treated as zeroes
in some cases, like expenditure, we are more than fine to assert 0 over missings
in other cases, it may not be so clear.

**Comment by Colleen-ODonnell** [comment]
We are going to interpret 0's and empty cells as missing values under the assumption that different interviewers record missing information differently. We decided on ways to denote missing values in #9
